gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    searchingActiveBorderColor:
      - cyan
      - bold
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
