[[language]]
name = "json"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.json"] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.jsonc"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright"]

[[language]]
name = "go"
language-servers = ["gopls"]
